/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UpdateManager;
import Model.DatabaseTools;
import Model.Ruang;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class HalamanUpdatePengajuan extends javax.swing.JFrame {

    /**
     * Creates new form HalamanStatusPengajuan
     */
    private int idRuang;
    private int idPengajuan;
    private boolean comboInit;
    
    UpdateManager updateManager;
    public HalamanUpdatePengajuan(UpdateManager updateManager,int idRuang, int idPengajuan) {
        initComponents();
        this.updateManager = updateManager;
        this.idRuang = idRuang;
        this.idPengajuan = idPengajuan;
        comboInit=false;
        
        populateComboBoxRuang();
        comboBoxRuang.setSelectedIndex(idRuang-1);
        comboInit=true;
        String query=String.format("select * from pengajuan join peminjam on pengajuan.nim = peminjam.nim join ruang on pengajuan.idRuang = ruang.idRuang where idPengajuan = %s",idPengajuan);
        ArrayList<String> arr = updateManager.populateUpdatePengajuan(query);
        try {
            tfNamaLembaga.setText(arr.get(0));
            tfFasilitas.setText(arr.get(1));
            tfKapasitas.setText(arr.get(2));
            tfDate.setText(arr.get(3));
            tfAwal.setText(arr.get(4));
            tfAkhir.setText(arr.get(5));
            
        } catch (Exception ex) {
            Logger.getLogger(HalamanUpdatePengajuan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ada error");
        }
        
        
    }

    
    public void populateComboBoxRuang(){
        String query = "select * from ruang";
        comboBoxRuang.removeAllItems();
        try {
            comboBoxRuang.removeAll();
            ArrayList<Ruang> arr = updateManager.populateComboBoxRuang(query);
            
            for(Ruang r : arr){
               comboBoxRuang.addItem(r.getNamaRuang());
            }
            } catch (Exception ex) {
            Logger.getLogger(HalamanStatusPengajuan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ada error saat mengisi combobox");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfKapasitas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNamaLembaga = new javax.swing.JTextField();
        comboBoxRuang = new javax.swing.JComboBox<>();
        tfDate = new javax.swing.JTextField();
        tfAwal = new javax.swing.JTextField();
        tfAkhir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfFasilitas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update Pengajuan");

        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Ruang");

        jLabel3.setText("Fasilitas");

        jLabel4.setText("Kapasitas");

        tfKapasitas.setEditable(false);
        tfKapasitas.setText("100");

        jLabel5.setText("Nama Lembaga Peminjam");

        jLabel6.setText("Tanggal Peminjaman");

        tfNamaLembaga.setText("Lembaga XYZ");

        comboBoxRuang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxRuang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxRuangItemStateChanged(evt);
            }
        });
        comboBoxRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRuangActionPerformed(evt);
            }
        });

        tfDate.setText("yyyy-mm-dd");

        tfAwal.setText("jTextField1");

        tfAkhir.setText("jTextField1");

        jLabel7.setText("Waktu Kegiatan Mulai");

        jLabel8.setText("Waktu Kegiatan Berakhir");

        tfFasilitas.setEditable(false);
        tfFasilitas.setColumns(20);
        tfFasilitas.setRows(5);
        jScrollPane1.setViewportView(tfFasilitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDate)
                                    .addComponent(tfAwal)
                                    .addComponent(tfAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxRuang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNamaLembaga, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))
                                .addGap(87, 87, 87))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNamaLembaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxRuangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxRuangItemStateChanged
        if(comboInit){
            String namaRuang = comboBoxRuang.getSelectedItem().toString();
            String query = String.format("select * from Ruang where namaRuang = '%s'",namaRuang);
            ArrayList<Ruang> arr= updateManager.populateTextFieldUpdate(query);
            try {
                tfFasilitas.setText(arr.get(0).getFasilitas());
                tfKapasitas.setText(Integer.toString(arr.get(0).getKapasitas()));
                } catch (Exception e) {
                Logger.getLogger(HalamanStatusPengajuan.class.getName()).log(Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(null, "Ada error saat mengisi daftar status pengajuan");
            }
        }   
    }//GEN-LAST:event_comboBoxRuangItemStateChanged

    private void comboBoxRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRuangActionPerformed
        
    }//GEN-LAST:event_comboBoxRuangActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        
//        String query = String.format("SELECT ((Select tanggalWaktuPengajuan from pengajuan where idPengajuan = %s)>CURRENT_DATE)", this.idPengajuan);
        String query = String.format("INSERT INTO `daftar_permintaan_update` (idPengajuan, idRuang,namaLembaga ,tanggalWaktuPeminjaman, waktuAwalPeminjaman, waktuAkhirPeminjaman) VALUES (%s, %s, '%s', '%s', %s, %s)", idPengajuan, idRuang, tfNamaLembaga.getText(), tfDate.getText(), tfAwal.getText(), tfAkhir.getText());
        int awal = Integer.parseInt(tfAwal.getText());
        int akhir = Integer.parseInt(tfAkhir.getText());
        try{
            if(awal <7){
                JOptionPane.showMessageDialog(null, "Waktu mulai kegiatan terlalu awal");
            }else if(akhir>21){
                JOptionPane.showMessageDialog(null, "Waktu kegiatan berakhir terlalu malam");
            }else if(awal>=akhir){
                JOptionPane.showMessageDialog(null, "Waktu kegiatan berakhir tidak boleh mendahului waktu kegiatan mulai");
            }else{
                updateManager.insertUpdatePengajuan(query);
                JOptionPane.showMessageDialog(null, "Perubahan berhasil diajukan");
                updateManager.showHalamanStatusPengajuan();
                this.hide();
            }
        }catch(Exception e){
            Logger.getLogger(HalamanStatusPengajuan.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Ada error");
        }
        
        
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        updateManager.showHalamanStatusPengajuan();
        this.hide();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], UpdateManager updateManager, int idRuang, int idPengajuan) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUpdatePengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUpdatePengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUpdatePengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUpdatePengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUpdatePengajuan(updateManager, idRuang, idPengajuan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> comboBoxRuang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAkhir;
    private javax.swing.JTextField tfAwal;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextArea tfFasilitas;
    private javax.swing.JTextField tfKapasitas;
    private javax.swing.JTextField tfNamaLembaga;
    // End of variables declaration//GEN-END:variables
}
